sonar.projectKey=atreyu-library-frontend
sonar.organization=pakodiazdev-1
sonar.projectName=Atreyu Library — Frontend

sonar.sources=src
sonar.exclusions=**/*.html,src/environments/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info

sonar.qualitygate.wait=true
